name = "Snowball"
uuid = "fb8f903a-0164-4e73-9ffe-431110250c3b"
authors = ["Avik Sengupta", "Julia Computing"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
